# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e88f784f63b55b4cb233a93b62c29e575a8e080fa54ac035ecc1852118a10a0f9f9948cb774455cbcffb38894ffd6d4ce796f608bd4534ce8133c871ba7e803b

test:
  secret_key_base: b5996051e373fa17e8f21b47dee29cc93495d7fde993215df3d0e5c9f298f6691562477780acc4b15cc9890e63244ac2cbc0cb679410c66f4508cf2ef7b1d47a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
